/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IMesonSwapInterface extends utils.Interface {
  functions: {
    "bondSwap(bytes32)": FunctionFragment;
    "cancelSwap(bytes32)": FunctionFragment;
    "executeSwap(bytes32,bytes,bytes32,bytes32,uint8,bool)": FunctionFragment;
    "postSwap(bytes,uint8,address,bytes32,bytes32,uint8)": FunctionFragment;
    "requestSwap(bytes,uint8)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "bondSwap", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "cancelSwap",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeSwap",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "postSwap",
    values: [
      BytesLike,
      BigNumberish,
      string,
      BytesLike,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "requestSwap",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "bondSwap", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancelSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeSwap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "postSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestSwap",
    data: BytesLike
  ): Result;

  events: {
    "SwapBonded(bytes32)": EventFragment;
    "SwapCancelled(bytes32)": EventFragment;
    "SwapExecuted(bytes32)": EventFragment;
    "SwapPosted(bytes32)": EventFragment;
    "SwapRequested(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapBonded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapPosted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapRequested"): EventFragment;
}

export type SwapBondedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapBondedEventFilter = TypedEventFilter<SwapBondedEvent>;

export type SwapCancelledEvent = TypedEvent<[string], { swapId: string }>;

export type SwapCancelledEventFilter = TypedEventFilter<SwapCancelledEvent>;

export type SwapExecutedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapExecutedEventFilter = TypedEventFilter<SwapExecutedEvent>;

export type SwapPostedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapPostedEventFilter = TypedEventFilter<SwapPostedEvent>;

export type SwapRequestedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapRequestedEventFilter = TypedEventFilter<SwapRequestedEvent>;

export interface IMesonSwap extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMesonSwapInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    bondSwap(
      swapId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelSwap(
      swapId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    executeSwap(
      swapId: BytesLike,
      recipient: BytesLike,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      depositToPool: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    postSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      initiator: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    requestSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  bondSwap(
    swapId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelSwap(
    swapId: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  executeSwap(
    swapId: BytesLike,
    recipient: BytesLike,
    r: BytesLike,
    s: BytesLike,
    v: BigNumberish,
    depositToPool: boolean,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  postSwap(
    encodedSwap: BytesLike,
    inTokenIndex: BigNumberish,
    initiator: string,
    r: BytesLike,
    s: BytesLike,
    v: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  requestSwap(
    encodedSwap: BytesLike,
    inTokenIndex: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    bondSwap(swapId: BytesLike, overrides?: CallOverrides): Promise<void>;

    cancelSwap(swapId: BytesLike, overrides?: CallOverrides): Promise<void>;

    executeSwap(
      swapId: BytesLike,
      recipient: BytesLike,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      depositToPool: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    postSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      initiator: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    requestSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    "SwapBonded(bytes32)"(swapId?: null): SwapBondedEventFilter;
    SwapBonded(swapId?: null): SwapBondedEventFilter;

    "SwapCancelled(bytes32)"(swapId?: null): SwapCancelledEventFilter;
    SwapCancelled(swapId?: null): SwapCancelledEventFilter;

    "SwapExecuted(bytes32)"(swapId?: null): SwapExecutedEventFilter;
    SwapExecuted(swapId?: null): SwapExecutedEventFilter;

    "SwapPosted(bytes32)"(swapId?: null): SwapPostedEventFilter;
    SwapPosted(swapId?: null): SwapPostedEventFilter;

    "SwapRequested(bytes32)"(swapId?: null): SwapRequestedEventFilter;
    SwapRequested(swapId?: null): SwapRequestedEventFilter;
  };

  estimateGas: {
    bondSwap(
      swapId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelSwap(
      swapId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    executeSwap(
      swapId: BytesLike,
      recipient: BytesLike,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      depositToPool: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    postSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      initiator: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    requestSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    bondSwap(
      swapId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelSwap(
      swapId: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    executeSwap(
      swapId: BytesLike,
      recipient: BytesLike,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      depositToPool: boolean,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    postSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      initiator: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    requestSwap(
      encodedSwap: BytesLike,
      inTokenIndex: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
