/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IMesonPoolsEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "SwapLocked(uint256)": EventFragment;
    "SwapReleased(uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapLocked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapReleased"): EventFragment;
}

export type SwapLockedEvent = TypedEvent<
  [BigNumber],
  { encodedSwap: BigNumber }
>;

export type SwapLockedEventFilter = TypedEventFilter<SwapLockedEvent>;

export type SwapReleasedEvent = TypedEvent<
  [BigNumber],
  { encodedSwap: BigNumber }
>;

export type SwapReleasedEventFilter = TypedEventFilter<SwapReleasedEvent>;

export interface IMesonPoolsEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMesonPoolsEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "SwapLocked(uint256)"(encodedSwap?: null): SwapLockedEventFilter;
    SwapLocked(encodedSwap?: null): SwapLockedEventFilter;

    "SwapReleased(uint256)"(encodedSwap?: null): SwapReleasedEventFilter;
    SwapReleased(encodedSwap?: null): SwapReleasedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
