/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IMesonSwapEventsInterface extends utils.Interface {
  functions: {};

  events: {
    "SwapBonded(bytes32)": EventFragment;
    "SwapCancelled(bytes32)": EventFragment;
    "SwapExecuted(bytes32)": EventFragment;
    "SwapPosted(bytes32)": EventFragment;
    "SwapRequested(bytes32)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "SwapBonded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapCancelled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapExecuted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapPosted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapRequested"): EventFragment;
}

export type SwapBondedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapBondedEventFilter = TypedEventFilter<SwapBondedEvent>;

export type SwapCancelledEvent = TypedEvent<[string], { swapId: string }>;

export type SwapCancelledEventFilter = TypedEventFilter<SwapCancelledEvent>;

export type SwapExecutedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapExecutedEventFilter = TypedEventFilter<SwapExecutedEvent>;

export type SwapPostedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapPostedEventFilter = TypedEventFilter<SwapPostedEvent>;

export type SwapRequestedEvent = TypedEvent<[string], { swapId: string }>;

export type SwapRequestedEventFilter = TypedEventFilter<SwapRequestedEvent>;

export interface IMesonSwapEvents extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IMesonSwapEventsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "SwapBonded(bytes32)"(swapId?: null): SwapBondedEventFilter;
    SwapBonded(swapId?: null): SwapBondedEventFilter;

    "SwapCancelled(bytes32)"(swapId?: null): SwapCancelledEventFilter;
    SwapCancelled(swapId?: null): SwapCancelledEventFilter;

    "SwapExecuted(bytes32)"(swapId?: null): SwapExecutedEventFilter;
    SwapExecuted(swapId?: null): SwapExecutedEventFilter;

    "SwapPosted(bytes32)"(swapId?: null): SwapPostedEventFilter;
    SwapPosted(swapId?: null): SwapPostedEventFilter;

    "SwapRequested(bytes32)"(swapId?: null): SwapRequestedEventFilter;
    SwapRequested(swapId?: null): SwapRequestedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
