/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MesonHelpersTestInterface extends utils.Interface {
  functions: {
    "checkReleaseSignature(bytes32,address,address,bytes32,bytes32,uint8)": FunctionFragment;
    "checkRequestSignature(bytes32,address,bytes32,bytes32,uint8)": FunctionFragment;
    "decodeSwapInput(bytes)": FunctionFragment;
    "encodeSwap(bytes,uint256,uint64,bytes4,bytes)": FunctionFragment;
    "getCoinType()": FunctionFragment;
    "getSwapId(address,uint256,uint64,bytes4,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkReleaseSignature",
    values: [BytesLike, string, string, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkRequestSignature",
    values: [BytesLike, string, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decodeSwapInput",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "encodeSwap",
    values: [BytesLike, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCoinType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSwapId",
    values: [string, BigNumberish, BigNumberish, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkReleaseSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkRequestSignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "decodeSwapInput",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "encodeSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCoinType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSwapId", data: BytesLike): Result;

  events: {};
}

export interface MesonHelpersTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MesonHelpersTestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkReleaseSignature(
      swapId: BytesLike,
      recipient: string,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    checkRequestSignature(
      swapId: BytesLike,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[void]>;

    decodeSwapInput(
      encodedSwap: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string, BigNumber]>;

    encodeSwap(
      inToken: BytesLike,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getCoinType(overrides?: CallOverrides): Promise<[string]>;

    getSwapId(
      inToken: string,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<[string]>;
  };

  checkReleaseSignature(
    swapId: BytesLike,
    recipient: string,
    signer: string,
    r: BytesLike,
    s: BytesLike,
    v: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  checkRequestSignature(
    swapId: BytesLike,
    signer: string,
    r: BytesLike,
    s: BytesLike,
    v: BigNumberish,
    overrides?: CallOverrides
  ): Promise<void>;

  decodeSwapInput(
    encodedSwap: BytesLike,
    overrides?: CallOverrides
  ): Promise<[BigNumber, string, BigNumber]>;

  encodeSwap(
    inToken: BytesLike,
    amount: BigNumberish,
    expireTs: BigNumberish,
    outChain: BytesLike,
    outToken: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  getCoinType(overrides?: CallOverrides): Promise<string>;

  getSwapId(
    inToken: string,
    amount: BigNumberish,
    expireTs: BigNumberish,
    outChain: BytesLike,
    outToken: BytesLike,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    checkReleaseSignature(
      swapId: BytesLike,
      recipient: string,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkRequestSignature(
      swapId: BytesLike,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    decodeSwapInput(
      encodedSwap: BytesLike,
      overrides?: CallOverrides
    ): Promise<[BigNumber, string, BigNumber]>;

    encodeSwap(
      inToken: BytesLike,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    getCoinType(overrides?: CallOverrides): Promise<string>;

    getSwapId(
      inToken: string,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {};

  estimateGas: {
    checkReleaseSignature(
      swapId: BytesLike,
      recipient: string,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    checkRequestSignature(
      swapId: BytesLike,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    decodeSwapInput(
      encodedSwap: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    encodeSwap(
      inToken: BytesLike,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCoinType(overrides?: CallOverrides): Promise<BigNumber>;

    getSwapId(
      inToken: string,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    checkReleaseSignature(
      swapId: BytesLike,
      recipient: string,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    checkRequestSignature(
      swapId: BytesLike,
      signer: string,
      r: BytesLike,
      s: BytesLike,
      v: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    decodeSwapInput(
      encodedSwap: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    encodeSwap(
      inToken: BytesLike,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCoinType(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getSwapId(
      inToken: string,
      amount: BigNumberish,
      expireTs: BigNumberish,
      outChain: BytesLike,
      outToken: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
