name: Main branch CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Build packages
        run: yarn run build:packages
      - name: Check generated abis/types
        run: build:types && git diff --exit-code
      - run: yarn test
